apiVersion: apps/v1
kind: Deployment
metadata:
  name: serviceb
  labels:
    app: serviceb
spec:
  replicas: 1
  selector:
    matchLabels:
      app: serviceb
  template:
    metadata:
      labels:
        app: serviceb
      annotations:
        dapr.io/enabled: "true"
        dapr.io/id: "servicebapp"
        dapr.io/port: "5000"
        dapr.io/log-level: "debug"
        dapr.io/config: "tracing"
    spec:
      containers:
      - name: servicea
        image: m009/serviceb:0.1
        resources:
          limits:
            memory: 128Mi
            cpu: 0.2
          requests:
            memory: 64Mi
            cpu: 0.1
        env:
          - name: ASPNETCORE_ENVIRONMENT
            value: Development
          - name: ASPNETCORE_URLS
            value: "http://+:5000"
        ports:
        - containerPort: 5000
        imagePullPolicy: Always

